### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by rgoalcast** [MITHaystack/science-casestudies#1]
I am trying to install scikit-discovery: 
pip install scikit-discovery
Getting this error: 
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_x/8x2mhn5n4ps1f2g1rpqx824r0000gn/T/pip-install-qv1xl7jb/GDAL/

How can I get scikit-discovery ?

**Comment by CodyRude** [comment]
Using ```pip install scikit-discovery``` will try and install all necessary dependencies. It looks like pip is failing on the library GDAL. This could be a permissions issue, or something else (depending on your operating system). Since this package depends on python 3, make sure your pip is using python 3.

I would recommend installing python and the dependencies (like gdal, etc...) using anaconda: https://www.anaconda.com/download/

Anaconda can handle installing packages like gdal, which heavily utilize C/C++ or FORTRAN libraries.

**Comment by rgoalcast** [comment]
> Command "/Users/ram/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_x/8x2mhn5n4ps1f2g1rpqx824r0000gn/T/pip-install-recoidjf/GDAL/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/_x/8x2mhn5n4ps1f2g1rpqx824r0000gn/T/pip-record-5jx14by_/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/_x/8x2mhn5n4ps1f2g1rpqx824r0000gn/T/pip-install-recoidjf/GDAL/


I am getting this after 
pip install scikit-discovery
command. 
Now, 
brew upgrade gdal
I am getting 
Error: gdal 2.3.1_1 already installed.

Now How can I overcome this problem ?

**Comment by CodyRude** [comment]
It looks like your using anaconda. Try installing GDAL using conda:

```conda install gdal```

**Comment by rgoalcast** [comment]
import skdiscovery.utilities.planetary.raster_management
Traceback (most recent call last):

  File "<ipython-input-6-373f4cc95db8>", line 1, in <module>
    import skdiscovery.utilities.planetary.raster_management

  File "/Users/anaconda3/lib/python3.6/site-packages/skdiscovery/utilities/planetary/raster_management.py", line 31, in <module>
    from osgeo import gdal, osr

  File "/Users/anaconda3/lib/python3.6/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()

  File "/Users/anaconda3/lib/python3.6/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)

  File "/Users/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)

  File "/Users/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)

ImportError: dlopen(/Users/ram/anaconda3/lib/python3.6/site-packages/osgeo/_gdal.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libgssapi_krb5.2.2.dylib
  Referenced from: /Users/ram/anaconda3/lib/libgdal.20.dylib
  Reason: image not found

How can I import ?

**Comment by CodyRude** [comment]
It looks like this is still a problem with GDAL. Make sure krb5 is installed:
```
conda install krb5
```
